development:
  domain: localhost
  port: 5984
  database: couch_spring
  
test:
  domain: localhost
  port: 5984
  database: couch_spring_test
  
production:
  protocol: https
  username: kane
  password: password
  domain: rubyghetto.com
  port: 5984
  database: couch_spring_for_go 
  
cloudant:
  protocol: https
  username: kane
  password: password
  domain: kane.cloudant.com
  database: couch_springy    